"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

# format = """
#   $username\
#   $hostname\
#   $directory\
#   $git_branch\
#   $git_state\
#   $git_status\
#   $nix_shell\
#   $git_metrics\
#   $fill\
#   $nodejs\
#   $line_break\
#   $character
# """

[hostname]
ssh_only = false
format = '[@$hostname]($style):'
style = "green bold"

[username]
show_always = true
format = '[$user]($style)'
style_user = "green bold"

[fill]
symbol = ' '

[directory]
truncate_to_repo = false
truncation_length = 10
style = 'bold blue'

[nodejs]
format = '[$symbol $version]($style)'
symbol = ''

[git_branch]
symbol = ''
format = '[$symbol $branch]($style)'
style = 'bold green'

[nix_shell]
format = '[$symbol]($style) '
symbol = '❄️'
style = 'bold blue'

[package]
disabled = true
